version: '3.8'

services:
  app:
    image: my-golang-app:latest
    ports:
      - "${APP_PORT}:8080"
    environment:
      - APP_ENV=production
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - postgres_eniqilo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_eniqilo: