name: Publish Docker Image

on:
  release:
    types:
      - published

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        env:
          DOCKER_REPOSITORY: mamxalf/eniqilo-store
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t $DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REPOSITORY:$IMAGE_TAG
